### ISSUE TITLE
Passing the ball

### ISSUE THREAD

**Issue by DonaldTsang** [celsriseup/awesome-booru#1]
Since this repo has not been updated for 3 months, would it be a good idea to pass the repo to @OAHOR ?
For reference: https://github.com/OAHOR/list-of-boorus

**Comment by DonaldTsang** [comment]
@celsriseup here is the question: Why is OAHOR's list have more useful information like setup type (yes people that browse boorus need to know this for downloading, see [Hydrus](https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts))?

> OAHORs repo doesn't even have a license, I would highly advice against contributing to such a shitty setup.

Okay I will request a license from their end.

**Comment by celsriseup** [comment]
Setup type? There's no setup type. You mean system?

How about you suggest that as an improvement to this list instead of just complaining about it?

> (yes people that browse boorus need to know this for downloading, see Hydrus)

Fucking scriptkiddies, can't even write their own software to download shit. 

> Okay I will request a license from their end.

Bruh, it's been 12 days, that repo is dead as fuck. 

Regardless, there are more problems with that list, for example why is rule34.xxx titled Rule34 Yaoi? That's just plain wrong. The table overflowing the Github article width is so shitty.

> Lastly, calm your salt

Stop projecting, I've been calm this whole time.

>  I get that you are from 4chan

I'm not, I'm from a place way worse than that.

>  no need to be such a lolcow about it.

You started by calling this list "badly aged", if you hadn't been such a fucking autist you would have realized that going around spewing written diarrhea on the internet doesn't win you any chicken tendies.

**Comment by DonaldTsang** [comment]
> Setup type? There's no setup type. You mean system?

Danbooru, Gelbooru, Moebooru etc. which is useful for scraping

> Fucking scriptkiddies, can't even write their own software to download shit.

The Hydrus Dev made a script system to off-load work to users.

> Regardless, there are more problems with that list, for example why is rule34.xxx titled Rule34 Yaoi? That's just plain wrong. The table overflowing the Github article width is so shitty.

Yeah that has to be cleaned as well.

> Stop projecting, I've been calm this whole time.

Then don't overreact with such negativity, act like a normie for once.

> I'm not, I'm from a place way worse than that.

Okay, so are you from 8kun by any chance? If not, where then?

> You started by calling this list "badly aged", if you hadn't been such a fucking autist you would have realized that going around spewing written diarrhea on the internet doesn't win you any chicken tendies.

Who said I want tendies?

**Comment by celsriseup** [comment]
> Danbooru, Gelbooru, Moebooru etc. which is useful for scraping

That's booru hosting software, and to be honest, that should be detectable by software like Hydrus, not something users should have to care about, in my opinion. But fine, we can add a different file that lists stuff like that. I'm not going to put it in the main README.md, since that is based on awesome-lists which has [a manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md), but we can put a notice and link to the file.

>  Then don't overreact with such negativity, act like a normie for once.

I'm not overreacting, you started the negativity by

1. Insulting me and the work I do for free by calling it "badly aged" even though it's only been three months
2. Using ad hominems, calling me names

How the hell do you except me not to give you the same treatment?

>  Okay, so are you from 8kun by any chance? If not, where then?

Why do you care? This is off topic. I'm not gonna dox myself.

> Who said I want tendies? I am doing this FOR FREE.

My god, you actually are autistic! My point with that last part was that you can't expect people to be nice to you when you're not nice to them. I am doing this for free as well, so shut the fuck up. You haven't even made any pull requests or starred the repo, so you're not even contributing, you're just complaining.

**Comment by DonaldTsang** [comment]
> I'm not overreacting, you started the negativity by
>  Insulting me and the work I do for free by calling it "badly aged" even though it's only been three months
> Using ad hominems, calling me names

Then why the upsets with having everything italicized in https://github.com/celsriseup/awesome-booru/issues/1#issuecomment-598879495 ? Why can't you take a criticism constructively and get so riled up and just say it kindly?

> Why do you care? This is off topic. I'm not gonna dox myself.

Maybe because unlike normies you are acting out, and I wonder if you are one of "those" who put emotions before rationality.

> My god, you actually are autistic! 

And you just confirmed my suspicion.

> My point with that last part was that you can't expect people to be nice to you when you're not nice to them.

As I said, if you can act kindly in the first reply, it wouldn't be like this.

> I am doing this for free as well, so shut the fuck up.

And I kindly refuse because due to your rudeness and agression.

> You haven't even made any pull requests or starred the repo, so you're not even contributing, you're just complaining.

If you want to put up a challenge then okay, I will do it.

**Comment by celsriseup** [comment]
@DonaldTsang 

>  As I said, if you can act kindly in the first reply, it wouldn't be like this.

You started first.

If you hadn't been an asshole to me in the first place, I'd have been much nicer to you.

Jesus christ.

Let me spell it out for you

1. I want you to close and edit your [issue](https://github.com/OAHOR/list-of-boorus/issues/7) to remove the highly offensive terminology ("badly aged") you used that is attacking my work, and apologize for using such terminology.
2. I want you to apologize for creating this "Passing the ball" issue because it is offensive to me when the repository isn't even that old and certainly not dead.
3. I want you to apologize for using ad hominems, calling me names.

To make amends, I will start by being the bigger person and saying:

**I apologize for calling you names.** It was an act of revenge and I will try not to do it again, so long as your behavior towards me and my work improves.

Go ahead and tell me if there is anything else you want me to do or apologize for to make amends if that's not enough.
